Build an ANN Regression model to predict the electrical energy output of a Combined Cycle Power Plant

Importing libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

Data preprocessing

Importing the dataset

In [ ]:
dataset = pd.read_excel('/content/Folds5x2_pp.xlsx')

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2)

Building the ANN  model

Initialize the model

In [ ]:
ann  =  tf.keras.models.Sequential()

Adding input layer and first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 , activation='relu'))# dense is used to connect input layer with hidden layer

Adding second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 , activation='relu'))

Adding output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

Part 3- Training the ANN model

Compile the ANN model

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

Train the ANN model on training set

In [ ]:
ann.fit(X_train,y_train,batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 219837.6719
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 39218.4375
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 290.7049
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 291.9832
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 283.9349
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 272.3253
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 261.8617
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 245.8746
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 238.3615
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 229.2745
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.5839
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 197.5257
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 187.0007
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 167.7897
Epoch 15/1

Predicting the results of test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[470.19 474.93]
 [441.99 435.78]
 [448.31 448.65]
 ...
 [431.38 435.7 ]
 [431.08 429.02]
 [431.41 443.01]]
